llama-7b:
  prompt_template: "llama-7b/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "huggyllama/llama-7b" # local path
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 2048
    temperature: 0.8
    top_p: 0.95
    do_sample: True
  pretty_name: "LLaMA 7B"
  link: "https://huggingface.co/huggyllama/llama-7b"