llama-2-70b-chat-hf-origin:
  prompt_template: "llama-2-7b-chat-hf/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "meta-llama/Llama-2-70b-chat-hf"
    model_kwargs:
      torch_dtype: 'float16'
    max_new_tokens: 400
    temperature: 0.7
    top_p: 1.0
    do_sample: True
    batch_size: 2
  pretty_name: "LLaMA2 Chat 70B"
  link: "https://huggingface.co/meta-llama/Llama-2-70b-chat-hf"
